# Not used right now, because LSB's start-stop-daemon doesn't know how
# to start daemons as a different user.

case "$1" in
  configure)

        if ! getent passwd shairport > /dev/null ; then
          echo 'Adding system-user for shairport' 1>&2
          adduser --system --quiet --no-create-home --disabled-login shairport
          echo 'Adding shairport to audio group' 1>&2
          adduser --quiet shairport audio
        fi

        ;;
esac
#DEBHELPER#
